version: "3"

services:
  simple_server_app:
      container_name: simple_server
      image: simple_server_app
      ports:
        - 50051:50051
  simple_client_app:
      container_name: simple_client
      image: simple_client_app
      depends_on: 
        - simple_server_app